### ISSUE TITLE
Generate raw data for select major cities (pm25).

### ISSUE THREAD

**Issue by abarciauskas-bgse** [DataKind-DC/openaq-tools#3]
2 outputs: 1 file like the current highcharts data for Shanghai for all data from 2015-2018 and 1 in the measurements API format.

- [ ] Kathmandu
- [ ] Delhi
- [ ] Ulaanbaatar
- [ ] Shanghai

**Comment by matthewcassi** [comment]
started pulling data for Kathmandu, Delhi, and Ulaanbaatar. will update later tonight

**Comment by matthewcassi** [comment]
i have the data ready for kathmandu, delhi, and ulaanbaatar but my git is all messed up so i need to fix that before i can push to the repo

**Comment by abarciauskas-bgse** [comment]
This is done.
